/**
 * HuggingFace Full Pipeline (100% Free)
 * ─────────────────────────────────────────────────────────────────
 * Step 1: Text → Image via HuggingFace Inference API (FLUX.1-schnell)
 * Step 2: Image → 3D GLB via stabilityai/stable-fast-3d Gradio Space
 * Step 3: Return GLB URL for display in Three.js
 */

import { Client } from "@gradio/client";
import { removeBackground } from "@imgly/background-removal";

export type HFPipelineStatus =
  | "TRANSLATING"
  | "GENERATING_IMAGE"
  | "REMOVING_BG"
  | "CONVERTING_3D"
  | "SUCCEEDED"
  | "FAILED";

export type HFProgressCallback = (
  progress: number,
  status: HFPipelineStatus,
  message: string
) => void;

// ─── قائمة نماذج توليد الصور المجانية على HuggingFace ────────────────────
const HF_IMAGE_MODELS = [
  "black-forest-labs/FLUX.1-schnell",
  "stabilityai/stable-diffusion-xl-base-1.0",
  "runwayml/stable-diffusion-v1-5",
];

// ─── قائمة مساحات تحويل الصورة إلى 3D على HuggingFace ───────────────────
const HF_3D_SPACES = [
  "stabilityai/stable-fast-3d",
];

/**
 * الدالة الرئيسية: من نص إلى مجسم 3D عبر HuggingFace مجاناً
 */
export async function huggingfaceTextTo3DPipeline(
  prompt: string,
  onProgress?: HFProgressCallback
): Promise<string> {
  // ── الخطوة 1: ترجمة النص لإنجليزية (للحصول على نتائج أفضل من AI) ──────
  onProgress?.(5, "TRANSLATING", "🌐 جاري ترجمة النص للذكاء الاصطناعي...");
  const englishPrompt = await translateToEnglish(prompt);
  const imagePrompt = `${englishPrompt}, high quality 3d render, isolated object, clean white background, studio lighting, photorealistic`;
  console.log("[HF Pipeline] Prompt:", imagePrompt);

  // ── الخطوة 2: توليد الصورة من Pollinations AI (بديل HF لتجاوز CORS) ─────────────
  onProgress?.(15, "GENERATING_IMAGE", "🤖 جاري توليد الصورة عبر Pollinations AI...");
  let imageBlob: Blob | null = null;

  try {
    onProgress?.(20, "GENERATING_IMAGE", `🔍 جاري سحب الصورة من السيرفر المفتوح...`);
    // استخدمنا Pollinations AI بدلاً من HF Inference لأنه لا يواجه مشكلة CORS في المتصفح
    const randomSeed = Math.floor(Math.random() * 1000000);
    const pollinationsUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(imagePrompt)}?seed=${randomSeed}&width=512&height=512&nologo=true`;
    
    const response = await fetch(pollinationsUrl);
    if (!response.ok) throw new Error("Pollinations API failed");
    
    imageBlob = await response.blob();
    console.log("[Pipeline] Image generated by Pollinations, size:", imageBlob.size);
  } catch (e) {
    console.warn(`[Pipeline] Image generation failed:`, e);
  }

  if (!imageBlob || imageBlob.size < 5000) {
    throw new Error("فشل توليد الصورة بسبب مشكلة في الاتصال. حاول مجدداً.");
  }

  // ── الخطوة 3: إزالة الخلفية (محلياً) ────────────────────────────────
  onProgress?.(45, "REMOVING_BG", "✂️ جاري إزالة الخلفية محلياً...");
  let cleanBlob: Blob;
  try {
    cleanBlob = await removeBackground(imageBlob, {
      model: "isnet_fp16",
      output: { format: "image/png", quality: 1 },
      publicPath: "https://static.imgly.com/@imgly/background-removal/1.7.0/",
    });
    console.log("[HF Pipeline] Background removed. Clean size:", cleanBlob.size);
  } catch (bgErr) {
    console.warn("[HF Pipeline] BG removal failed, using raw image:", bgErr);
    cleanBlob = imageBlob;
  }

  // ── الخطوة 4: تحويل الصورة إلى 3D عبر HuggingFace Space ─────────────
  onProgress?.(60, "CONVERTING_3D", "🏗️ جاري الاتصال بـ Stable Fast 3D على HuggingFace...");

  for (const spaceId of HF_3D_SPACES) {
    try {
      onProgress?.(65, "CONVERTING_3D", `⚡ جاري المعالجة في ${spaceId}...`);
      const glbUrl = await convertImageTo3DGradio(cleanBlob, spaceId, (msg) => {
        onProgress?.(70 + Math.random() * 20, "CONVERTING_3D", msg);
      });
      onProgress?.(100, "SUCCEEDED", "🎉 المجسم الثلاثي الأبعاد جاهز!");
      return glbUrl;
    } catch (e) {
      console.warn(`[HF Pipeline] Space ${spaceId} failed:`, e);
      continue;
    }
  }

  throw new Error("فشل تحويل الصورة إلى 3D. خوادم HuggingFace قد تكون في وضع السكون. حاول مرة أخرى.");
}

// ─── توليد صورة عبر HuggingFace Inference API (مجاني) ───────────────────
async function fetchImageFromHFInference(prompt: string, modelId: string): Promise<Blob> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 45000); // 45s timeout

  try {
    const response = await fetch(
      `https://api-inference.huggingface.co/models/${modelId}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Accept": "image/png,image/jpeg,image/*",
        },
        body: JSON.stringify({
          inputs: prompt,
          parameters: {
            width: 512,
            height: 512,
            num_inference_steps: 4, // سريع للنماذج المدعومة
            guidance_scale: 0,
          },
          options: { wait_for_model: true },
        }),
        signal: controller.signal,
      }
    );

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`HF API ${response.status}: ${text.substring(0, 200)}`);
    }

    const blob = await response.blob();
    if (!blob.type.startsWith("image/")) {
      throw new Error(`Not an image response: ${blob.type}`);
    }
    return blob;
  } finally {
    clearTimeout(timeout);
  }
}

// ─── تحويل صورة إلى 3D عبر Gradio Space ─────────────────────────────────
async function convertImageTo3DGradio(
  imageBlob: Blob,
  spaceId: string,
  onMsg?: (msg: string) => void
): Promise<string> {
  onMsg?.("جاري الاتصال بالـ Space على HuggingFace...");
  const app = await withTimeout(
    Client.connect(spaceId),
    30000
  );

  onMsg?.("جاري رفع الصورة ومعالجتها إلى مجسم 3D...");
  const result = (await withTimeout(
    app.predict("/run", [imageBlob, 0.85, 512, "none"]),
    120000
  )) as any;

  const data = result?.data;
  let glbUrl = "";

  if (Array.isArray(data)) {
    for (const item of data) {
      if (item?.url?.includes(".glb") || item?.name?.includes(".glb")) {
        glbUrl = item.url ?? item.name;
        break;
      }
    }
    if (!glbUrl) {
      for (const item of data) {
        if (item?.url) { glbUrl = item.url; break; }
      }
    }
  }

  if (!glbUrl) {
    throw new Error("NO_GLB: لم يتم العثور على ملف 3D في استجابة HuggingFace");
  }

  return glbUrl;
}

// ─── ترجمة النص لإنجليزية عبر Google Translate مجاناً ───────────────────
async function translateToEnglish(text: string): Promise<string> {
  const hasArabic = /[\u0600-\u06FF]/.test(text);
  if (!hasArabic) return text;

  try {
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=ar&tl=en&dt=t&q=${encodeURIComponent(text)}`;
    const res = await fetch(url);
    if (res.ok) {
      const data = await res.json();
      if (data?.[0]?.[0]?.[0]) return data[0][0][0];
    }
  } catch (e) {
    console.warn("[Translate] Failed:", e);
  }

  return text; // return original if translation fails
}

// ─── Promise مع timeout ───────────────────────────────────────────────────
function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`TIMEOUT after ${ms}ms`)), ms);
    promise.then(
      (v) => { clearTimeout(timer); resolve(v); },
      (e) => { clearTimeout(timer); reject(e); }
    );
  });
}
